#!/bin/sh

prog=tpolyroot
out=/tmp/"$prog$$.out"
correct_out=/tmp/"$prog$$correct.out"
abserr=1.e-10

cat > "$correct_out" << "END"
n = 0:  roots = -1 0.5 -0.866025
n = 1:  roots = 0 0 0
n = 2:  roots = -3 -3 0
n = 3:  roots = 0 1 2
END
"$prog" > "$out"
if ndiff -abserr $abserr "$correct_out" "$out" > /dev/null 2>&1; then
	rm -f "$correct_out" "$out"
	exit 0
fi
exit 1
