#!/bin/sh

prog=tVector3
out=/tmp/"$prog$$.out"
correct_out=/tmp/"$prog$$correct.out"
abserr=1.e-10

cat > "$correct_out" << "END"
b: 1 2 3
A:
1 2 3
0 1 4
0 0 1
trace is:
3
transpose is:
1 0 0
2 1 0
3 4 1
deviator is:
0 2 3
0 0 4
0 0 0
F:
1 -2 5
-0 1 -4
0 -0 1
x: 12 -10 3
A*x: 1 2 3
END
"$prog" > "$out"
if ndiff -abserr $abserr "$correct_out" "$out" > /dev/null 2>&1; then
	rm -f "$correct_out" "$out"
	exit 0
fi
exit 1
