#!/bin/sh

prog=tVector1
out=/tmp/"$prog$$.out"
correct_out=/tmp/"$prog$$correct.out"
abserr=1.e-10

cat > "$correct_out" << "END"
b: 1
A:
2
transpose is:
2
trace is:
2
deviator is:
0
F:
0.5
x: 0.5
A*x: 1
evals of A: 2
evects of A:
1
B:
1.1
evals of B: 1.1
evects of B:
1
END
"$prog" > "$out"
if ndiff -abserr $abserr "$correct_out" "$out" > /dev/null 2>&1; then
	rm -f "$correct_out" "$out"
	exit 0
fi
exit 1
